class Football:
    """Football"""
    total = 0

    def __init__(self,name,number,position):
        self.name = name
        self.number = number
        self.position = position
        Football.total += 1

    def write(self):
        print(self.name,self.number,self.position) 

def main():
    f1 = Football("Андрей Пятов","12","Вратарь")
    f2 = Football("Денис Бойко","-","Вратарь")
    f3 = Football("Андрей Лунин","23","Вратарь")
    f4 = Football("Георгий Бущан","1","Вратарь")
    f5 = Football("Юрий Панькив","-","Вратарь")
    f6 = Football("Николай Матвиенко","22","Защитник")
    f7 = Football("Александр Караваев","21","Защитник")
    f8 = Football("Сергей Кривцов","4","Защитник")
    f9 = Football("Эдуард Соболь","2","Защитник")
    f10 = Football("Никита Бурда","-","Защитник")
    f11 = Football("Виталий Миколенко","-","Защитник")
    f12 = Football("Сергей Болбат","-","Защитник")
    f13 = Football("Игорь Пластун","3","Защитник")
    f14 = Football("Артём Шабанов","-","Защитник")
    f15 = Football("Александр Тымчик","18","Защитник")
    f16 = Football("Богдан Михайличенко","16","Защитник")
    f17 = Football("Валерий Бондарь","-","Защитник")
    f18 = Football("Александр Сирота","-","Защитник")
    f19 = Football("Денис Попов","-","Защитник")
    f20 = Football("Андрей Ярмоленко","7","Полузащитник")
    f21 = Football("Евгений Коноплянка","10","Полузащитник") 
    f22 = Football("Тарас Степаненко","6","Полузащитник")
    f23 = Football("Александр Зинченко","17","Полузащитник")
    f24 = Football("Сергей Сидорчук","5","Полузащитник")
    f25 = Football("Руслан Малиновский","8","Полузащитник")
    f26 = Football("Виктор Коваленко","20","Полузащитник")
    f27 = Football("Роман Безус","-","Полузащитник")
    f28 = Football("Виктор Цыганков","15","Полузащитник")
    f29 = Football("Марлос","11","Полузащитник")
    f30 = Football("Виталий Буяльский","-","Полузащитник")
    f31 = Football("Владимир Шепелев","-","Полузащитник")
    f32 = Football("Евгений Макаренко","-","Полузащитник")
    f33 = Football("Николай Шапаренко","-","Полузащитник")
    f34 = Football("Игорь Харатин","14","Полузащитник")
    f35 = Football("Александр Зубков","-","Полузащитник")
    f36 = Football("Роман Яремчук","9","Нападающий")
    f37 = Football("Жуниор Мораес","19","Нападающий")
    f38 = Football("Владислав Супряга","13","Нападающий")
    f1.write()
    f2.write()
    f3.write()
    f4.write()
    f5.write()
    f6.write()
    f7.write()
    f8.write()
    f9.write()
    f10.write()
    f11.write()
    f12.write()
    f13.write()
    f14.write()
    f15.write()
    f16.write()
    f17.write()
    f18.write()
    f19.write()
    f20.write()
    f21.write()
    f22.write()
    f23.write()
    f24.write()
    f25.write()
    f26.write()
    f27.write()
    f28.write()
    f29.write()
    f30.write()
    f31.write()
    f32.write()
    f33.write()
    f34.write()
    f35.write()
    f36.write()
    f37.write()
    f38.write()
    print(Football.total)

main()        